(define (sum term a next b)
  (define (iter a result)
    (if (> a b)
        result
        (iter (next a) (+ result (term a)))
        )
    )
  (iter a 0)
  )

(define (sum-int a b)
  (define (id a) a)
  (define (inc a) (+ a 1))
  (sum id a inc b)
  )
