(define (fringe items)
  (define (iter items result)
    (cond ((null? items) result)
          ((pair? items)
           (iter (car items) (iter (cdr items) result)))
          (else (cons items result)))
    )
  (trace-entry iter)
  (iter items ())
  )
