(define (count-change amount)
  (define (cc remain)
    (cond ((= remain 0) 1)
          ((< remain 0) 0)
          (else (+ (cc (- remain 1))
                   (cc (- remain 5))
                   (cc (- remain 10))
                   (cc (- remain 20))
                   (cc (- remain 50))
                   )
                )
        )
    )
  (cc amount)
  )
